select
  mm_dd
  ,month
  ,region
  ,period
  ,min_year
  ,max_year
  ,years_count
  ,electric_cdd_normal
  ,electric_hdd_normal
  ,gas_cdd_normal
  ,gas_hdd_normal
  ,population_cdd_normal
  ,population_hdd_normal
  ,tdd_normal
  ,electric_cdd_min
  ,electric_hdd_min
  ,gas_cdd_min
  ,gas_hdd_min
  ,population_cdd_min
  ,population_hdd_min
  ,tdd_min
  ,electric_cdd_max
  ,electric_hdd_max
  ,gas_cdd_max
  ,gas_hdd_max
  ,population_cdd_max
  ,population_hdd_max
  ,tdd_max
  ,electric_cdd_stddev
  ,electric_hdd_stddev
  ,gas_cdd_stddev
  ,gas_hdd_stddev
  ,population_cdd_stddev
  ,population_hdd_stddev
  ,tdd_stddev
from wsi_cleaned.wdd_normals_daily
