select
  forecast_rank
  ,forecast_label
  ,forecast_execution_datetime
  ,forecast_execution_date
  ,cycle
  ,forecast_date
  ,count_forecast_days
  ,max_forecast_days
  ,model
  ,bias_corrected
  ,region
  ,electric_cdd
  ,electric_hdd
  ,gas_cdd
  ,gas_hdd
  ,pw_cdd
  ,pw_hdd
  ,electric_cdd_diff_run_over_run
  ,electric_hdd_diff_run_over_run
  ,gas_cdd_diff_run_over_run
  ,gas_hdd_diff_run_over_run
  ,pw_cdd_diff_run_over_run
  ,pw_hdd_diff_run_over_run
from wsi_cleaned.wdd_forecasts_daily
