select
  gas_day
  ,trade_date
  ,hh_balmo
  ,transco_st85_balmo
  ,pine_prarie_balmo
  ,houston_ship_channel_balmo
  ,waha_balmo
  ,ngpl_txok_balmo
  ,transco_zone_5_south_balmo
  ,tetco_m3_balmo
  ,agt_balmo
  ,iroquois_z2_balmo
  ,socal_cg_balmo
  ,pge_cg_balmo
  ,cig_balmo
  ,ngpl_midcon_balmo
  ,michcon_balmo
from ice_python_cleaned.ice_python_balmo
