select
  datetime
  ,date
  ,hour_ending
  ,gas_day
  ,trade_date
  ,hh_cash
  ,transco_st85_cash
  ,pine_prarie_cash
  ,waha_cash
  ,houston_ship_channel_cash
  ,ngpl_txok_cash
  ,transco_zone_5_south_cash
  ,tetco_m3_cash
  ,agt_cash
  ,iroquois_z2_cash
  ,socal_cg_cash
  ,pge_cg_cash
  ,cig_cash
  ,ngpl_midcon_cash
  ,michcon_cash
from ice_python_cleaned.ice_python_next_day_gas_hourly
