version: 2

models:
  - name: miso_lmps_hourly
    description: '{{ doc("miso_mart_lmps_hourly") }}'
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'
        tests:
          - not_null
      - name: hub
        description: "MISO pricing hub name."
        tests:
          - not_null
      - name: market
        description: '{{ doc("col_market") }}'
        tests:
          - not_null
          - accepted_values:
              values: ['da', 'rt', 'dart']

  - name: miso_lmps_daily
    description: '{{ doc("miso_mart_lmps_daily") }}'
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
        tests:
          - not_null
      - name: period
        description: '{{ doc("col_period") }}'
        tests:
          - not_null
          - accepted_values:
              values: ['flat', 'onpeak', 'offpeak']
