select
  sftp_date
  ,sftp_upload_timestamp
  ,created_at
  ,updated_at
  ,record_i_d
  ,firm
  ,office
  ,rr
  ,account
  ,exchange_name
  ,exchange_name_3dig
  ,futures_code
  ,symbol
  ,printable_trade_price
  ,cash_amount
  ,sub_account
  ,spread_code
  ,trade_type
  ,comment_code
  ,exec_broker
  ,opp_broker
  ,opp_firm
  ,gi_code
  ,gi_firm
  ,curr_symbol
  ,prod_curr
  ,prod_type
  ,exec_time
  ,opt_exp_date
  ,last_trd_date
  ,traded_exchg
  ,sub_exchange
  ,source_refrnce
  ,exch_comm_cd
  ,mult_factor
  ,chit_number
  ,isin
  ,mic
  ,row_number_for_trades
  ,trade_date
  ,cusip
  ,tracer
  ,order_number
  ,instrument_description
  ,description
  ,contract_year_month
  ,contract_year
  ,contract_month
  ,contract_day
  ,put_call
  ,strike_price
  ,b_s
  ,qty
  ,trade_status
  ,is_option
  ,exchange_name_cleaned
  ,qty_cleaned
  ,account_cleaned
  ,futures_contract_month
  ,futures_contract_month_y
  ,futures_contract_month_yy
  ,account_name
  ,product_code_grouping
  ,product_code_region
  ,product_code_underlying
  ,bbg_exchange_code
  ,ice_product_code
  ,ice_product_code_underlying
  ,cme_product_code
  ,bbg_product_code
from trades_cleaned.clear_street_intraday_trades
