select
  sftp_date
  ,trade_date
  ,clear_street_account
  ,exchange_name
  ,product_code_grouping
  ,product_code_region
  ,exchange_code
  ,is_option
  ,put_call
  ,strike_price
  ,contract_yyyymm
  ,contract_year
  ,contract_month
  ,contract_day
  ,contract_description
  ,ice_product_code
  ,ice_product_code_underlying
  ,cme_product_code
  ,trade_price_total
  ,trade_price_acim
  ,trade_price_andy
  ,trade_price_mac
  ,trade_price_pnt
  ,trade_price_dickson
  ,trade_price_titan
  ,qty_total
  ,qty_acim
  ,qty_andy
  ,qty_mac
  ,qty_pnt
  ,qty_dickson
  ,qty_titan
from trades_cleaned.clear_street_intraday_trades_grouped
