select
  sftp_date
  ,sftp_upload_timestamp
  ,clear_date
  ,clear_status
  ,account
  ,trader
  ,exchange_name
  ,exchange_code
  ,put_call
  ,strike_price
  ,contract_yyyymm
  ,contract_year
  ,contract_month
  ,trade_date
  ,contract_description
  ,buy_sell
  ,qty
  ,trade_price
  ,source_table
  ,is_option
  ,futures_contract_month
  ,futures_contract_month_y
  ,futures_contract_month_yy
  ,account_name
  ,product_code_grouping
  ,product_code_region
  ,product_code_underlying
  ,ice_product_code
  ,ice_product_code_underlying
  ,cme_product_code
from trades_cleaned.marex_allocated_trades
