version: 2

models:
  - name: nyiso_lmps_hourly
    description: '{{ doc("nyiso_mart_lmps_hourly") }}'
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'
        tests:
          - not_null
      - name: hub
        description: "NYISO pricing zone name."
        tests:
          - not_null
      - name: market
        description: '{{ doc("col_market") }}'
        tests:
          - not_null
          - accepted_values:
              values: ['da', 'rt', 'dart']
