version: 2

models:
  - name: staging_v1_ea_pjm_power_model_monthly
    description: '{{ doc("ea_staging_pjm_power_model") }}'
    columns:
      - name: date
        description: '{{ doc("ea_col_date") }}'
        tests:
          - not_null
      - name: coal_generation_ea_price_mw
        description: '{{ doc("ea_col_coal_generation_ea_price_mw") }}'
      - name: coal_generation_fwd_price_mw
        description: '{{ doc("ea_col_coal_generation_fwd_price_mw") }}'
      - name: ng_generation_ea_price_mw
        description: '{{ doc("ea_col_ng_generation_ea_price_mw") }}'
      - name: ng_generation_fwd_price_mw
        description: '{{ doc("ea_col_ng_generation_fwd_price_mw") }}'
      - name: nuclear_generation_mw
        description: '{{ doc("ea_col_nuclear_generation_mw") }}'
      - name: solar_generation_mw
        description: '{{ doc("ea_col_solar_generation_mw") }}'
      - name: wind_generation_mw
        description: '{{ doc("ea_col_wind_generation_mw") }}'
      - name: hydro_generation_mw
        description: '{{ doc("ea_col_hydro_generation_mw") }}'
      - name: other_generation_mw
        description: '{{ doc("ea_col_other_generation_mw") }}'
      - name: thermal_generation_norm_weather_mw
        description: '{{ doc("ea_col_thermal_generation_norm_weather_mw") }}'
      - name: net_imports_mw
        description: '{{ doc("ea_col_net_imports_mw") }}'
      - name: demand_mw
        description: '{{ doc("ea_col_demand_mw") }}'
      - name: ng_demand_ea_price_bcf_per_d
        description: '{{ doc("ea_col_ng_demand_ea_price_bcf_per_d") }}'
      - name: ng_demand_fwd_price_bcf_per_d
        description: '{{ doc("ea_col_ng_demand_fwd_price_bcf_per_d") }}'
      - name: ng_equiv_demand_norm_weather_bcf_per_d
        description: '{{ doc("ea_col_ng_equiv_demand_norm_weather_bcf_per_d") }}'

  - name: staging_v1_ea_pjm_price_hr_spark_monthly
    description: '{{ doc("ea_staging_pjm_price_hr_spark") }}'
    columns:
      - name: date
        description: '{{ doc("ea_col_date") }}'
        tests:
          - not_null
      - name: on_peak_power_price_usd_per_mwh
        description: '{{ doc("ea_col_on_peak_power_price") }}'
      - name: on_peak_heat_rate_mmbtu_per_mwh
        description: '{{ doc("ea_col_on_peak_heat_rate") }}'
      - name: on_peak_dirty_spark_spread_usd_per_mwh
        description: '{{ doc("ea_col_on_peak_dirty_spark_spread") }}'

  - name: staging_v1_ea_pjm_load_model_monthly
    description: '{{ doc("ea_staging_pjm_load_model") }}'
    columns:
      - name: date
        description: '{{ doc("ea_col_date") }}'
        tests:
          - not_null
      - name: load_norm_weather_mw
        description: '{{ doc("ea_col_load_norm_weather_mw") }}'
      - name: actual_load_norm_weather_mw
        description: '{{ doc("ea_col_actual_load_norm_weather_mw") }}'

  - name: staging_v1_ea_pjm_installed_capacity_monthly
    description: '{{ doc("ea_staging_pjm_installed_capacity") }}'
    columns:
      - name: date
        description: '{{ doc("ea_col_date") }}'
        tests:
          - not_null
      - name: ng_capacity_mw
        description: "EA forecast for PJM natural gas installed capacity (MW)."
      - name: coal_capacity_mw
        description: "EA forecast for PJM coal installed capacity (MW)."
      - name: nuclear_capacity_mw
        description: "EA forecast for PJM nuclear installed capacity (MW)."
      - name: oil_capacity_mw
        description: "EA forecast for PJM oil products installed capacity (MW)."
      - name: solar_capacity_mw
        description: "EA forecast for PJM solar installed capacity (MW)."
      - name: onshore_wind_capacity_mw
        description: "EA forecast for PJM onshore wind installed capacity (MW)."
      - name: offshore_wind_capacity_mw
        description: "EA forecast for PJM offshore wind installed capacity (MW)."
      - name: hydro_capacity_mw
        description: "EA forecast for PJM hydro installed capacity (MW)."
      - name: battery_capacity_mw
        description: "EA forecast for PJM battery installed capacity (MW)."

  - name: staging_v1_ea_pjm_dispatch_costs_monthly
    description: '{{ doc("ea_staging_pjm_dispatch_costs") }}'
    columns:
      - name: date
        description: '{{ doc("ea_col_date") }}'
        tests:
          - not_null
      - name: ng_high_hr_ccgt_dispatch_cost_pjm_w
        description: "NG dispatch cost for high heat rate CCGT in PJM W ($/MWh, RGGI included)."
      - name: ng_low_hr_ccgt_dispatch_cost_pjm_w
        description: "NG dispatch cost for low heat rate CCGT in PJM W ($/MWh, RGGI included)."
      - name: ng_ct_dispatch_cost_pjm_w
        description: "NG dispatch cost for CT in PJM W ($/MWh, RGGI included)."
      - name: ng_st_dispatch_cost_pjm_w
        description: "NG dispatch cost for ST in PJM W ($/MWh, RGGI included)."
      - name: diesel_ccgt_dispatch_cost_pjm_w
        description: "Diesel dispatch cost for CCGT in PJM W ($/MWh, RGGI included)."
      - name: diesel_ct_dispatch_cost_pjm_w
        description: "Diesel dispatch cost for CT in PJM W ($/MWh, RGGI included)."
      - name: fuel_oil_st_dispatch_cost_pjm_w
        description: "Fuel oil dispatch cost for ST in PJM W ($/MWh, RGGI included)."
      - name: ng_high_hr_ccgt_fuel_cost_nihub
        description: "NG fuel cost for high heat rate CCGT in PJM Nihub ($/MWh)."
      - name: ng_low_hr_ccgt_fuel_cost_nihub
        description: "NG fuel cost for low heat rate CCGT in PJM Nihub ($/MWh)."
      - name: ng_ct_fuel_cost_nihub
        description: "NG fuel cost for CT in PJM Nihub ($/MWh)."
      - name: ng_st_fuel_cost_nihub
        description: "NG fuel cost for ST in PJM Nihub ($/MWh)."
      - name: ng_high_hr_ccgt_fuel_cost_adhub
        description: "NG fuel cost for high heat rate CCGT in PJM Adhub ($/MWh)."
      - name: ng_low_hr_ccgt_fuel_cost_adhub
        description: "NG fuel cost for low heat rate CCGT in PJM Adhub ($/MWh)."
      - name: ng_ct_fuel_cost_adhub
        description: "NG fuel cost for CT in PJM Adhub ($/MWh)."
      - name: ng_st_fuel_cost_adhub
        description: "NG fuel cost for ST in PJM Adhub ($/MWh)."
      - name: ng_high_hr_ccgt_fuel_cost_pjm_w
        description: "NG fuel cost for high heat rate CCGT in PJM W ($/MWh)."
      - name: ng_low_hr_ccgt_fuel_cost_pjm_w
        description: "NG fuel cost for low heat rate CCGT in PJM W ($/MWh)."
      - name: ng_ct_fuel_cost_pjm_w
        description: "NG fuel cost for CT in PJM W ($/MWh)."
      - name: ng_st_fuel_cost_pjm_w
        description: "NG fuel cost for ST in PJM W ($/MWh)."
      - name: ng_high_hr_ccgt_fuel_cost_dominion
        description: "NG fuel cost for high heat rate CCGT in PJM Dominion ($/MWh)."
      - name: ng_low_hr_ccgt_fuel_cost_dominion
        description: "NG fuel cost for low heat rate CCGT in PJM Dominion ($/MWh)."
      - name: ng_ct_fuel_cost_dominion
        description: "NG fuel cost for CT in PJM Dominion ($/MWh)."
      - name: ng_st_fuel_cost_dominion
        description: "NG fuel cost for ST in PJM Dominion ($/MWh)."
      - name: ng_high_hr_ccgt_dispatch_cost_dominion
        description: "NG dispatch cost for high heat rate CCGT in PJM Dominion ($/MWh, RGGI included)."
      - name: ng_low_hr_ccgt_dispatch_cost_dominion
        description: "NG dispatch cost for low heat rate CCGT in PJM Dominion ($/MWh, RGGI included)."
      - name: ng_ct_dispatch_cost_dominion
        description: "NG dispatch cost for CT in PJM Dominion ($/MWh, RGGI included)."
      - name: ng_st_dispatch_cost_dominion
        description: "NG dispatch cost for ST in PJM Dominion ($/MWh, RGGI included)."
      - name: bit_coal_high_transport_dispatch_cost_pjm_w
        description: "Bituminous coal dispatch cost with high transport cost in PJM W ($/MWh, RGGI included)."
      - name: bit_coal_low_transport_dispatch_cost_pjm_w
        description: "Bituminous coal dispatch cost with low transport cost in PJM W ($/MWh, RGGI included)."
      - name: bit_coal_mid_transport_dispatch_cost_pjm_w
        description: "Bituminous coal dispatch cost with mid transport cost in PJM W ($/MWh, RGGI included)."
      - name: bit_coal_high_transport_fuel_cost_pjm_w
        description: "Bituminous coal fuel cost with high transport cost in PJM W ($/MWh)."
      - name: bit_coal_low_transport_fuel_cost_pjm_w
        description: "Bituminous coal fuel cost with low transport cost in PJM W ($/MWh)."
      - name: bit_coal_mid_transport_fuel_cost_pjm_w
        description: "Bituminous coal fuel cost with mid transport cost in PJM W ($/MWh)."
      - name: sub_bit_coal_high_transport_fuel_cost_nihub
        description: "Sub-bituminous coal fuel cost with high transport cost in PJM Nihub ($/MWh)."
      - name: sub_bit_coal_low_transport_fuel_cost_nihub
        description: "Sub-bituminous coal fuel cost with low transport cost in PJM Nihub ($/MWh)."
      - name: sub_bit_coal_mid_transport_fuel_cost_nihub
        description: "Sub-bituminous coal fuel cost with mid transport cost in PJM Nihub ($/MWh)."
