version: 2

sources:

  - name: genscape_v2
    schema: genscape
    description: '{{ doc("genscape_overview") }}'
    tables:
      - name: gas_production_forecast_v2_2025_09_23
        description: '{{ doc("genscape_source") }}'
        loaded_at_field: "reportdate"
        freshness:
          warn_after: { count: 48, period: hour }
          error_after: { count: 72, period: hour }

      - name: daily_pipeline_production_v2_2026_mar_10
        description: '{{ doc("genscape_daily_pipeline_production_source") }}'
        loaded_at_field: "reportdate"
        freshness:
          warn_after: { count: 48, period: hour }
          error_after: { count: 72, period: hour }

      - name: daily_power_estimate
        description: '{{ doc("genscape_daily_power_estimate_source") }}'
