version: 2

sources:

  - name: gridstatus_v1
    schema: gridstatus
    description: '{{ doc("miso_overview") }}'
    tables:
      - name: miso_lmp_day_ahead_hourly
        description: "MISO day-ahead hourly LMPs by location from GridStatus."
      - name: miso_lmp_real_time_5_min
        description: "MISO real-time 5-minute LMPs by location from GridStatus."
