select
  date
  ,is_iso
  ,time_zone
  ,respondent
  ,region
  ,balancing_authority_name
  ,total_mw
  ,renewables_mw
  ,thermal_mw
  ,wind_mw
  ,solar_mw
  ,natural_gas_mw
  ,coal_mw
  ,oil_mw
  ,nuclear_mw
  ,hydro_mw
  ,pumped_storage_mw
  ,geothermal_mw
  ,battery_mw
  ,solar_battery_mw
  ,wind_battery_mw
  ,other_energy_storage_mw
  ,unknown_energy_storage_mw
  ,other_mw
  ,unknown_mw
  ,natural_gas_pct_of_thermal
  ,coal_pct_of_thermal
from eia_cleaned.eia_930_daily
