version: 2

models:
  - name: source_v1_nyiso_da_hrl_lmps
    description: "Normalized NYISO day-ahead hourly LMPs pivoted to wide format by zone."
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'

  - name: source_v1_nyiso_rt_hrl_lmps
    description: "Normalized NYISO real-time hourly LMPs (5-min averaged) pivoted to wide format by zone."
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'
