version: 2

sources:

  - name: gridstatus_v1
    schema: gridstatus
    description: '{{ doc("spp_overview") }}'
    tables:
      - name: spp_lmp_day_ahead_hourly
        description: "SPP day-ahead hourly LMPs by location from GridStatus."
      - name: spp_lmp_real_time_5_min
        description: "SPP real-time 5-minute LMPs by location from GridStatus."
