{{
  config(
    materialized='ephemeral'
  )
}}

-- ICE EXCHANGE ACTIVITY REPORT — RAW SOURCE

SELECT
     file_name
    ,deal_type
    ,trade_date
    ,trade_time
    ,deal_id
    ,leg_id
    ,orig_id
    ,b_s
    ,product
    ,hub
    ,contract
    ,begin_date
    ,end_date
    ,clearing_acct
    ,cust_acct
    ,clearing_firm
    ,price
    ,price_units
    ,option
    ,strike
    ,strike2
    ,style
    ,lots
    ,total_quantity
    ,qty_units
    ,tt
    ,brk
    ,trader
    ,memo
    ,clearing_venue
    ,user_id
    ,source
    ,link_id
    ,usi
    ,authorized_trader_id
    ,location
    ,meter
    ,lead_time
    ,waiver_ind
    ,trade_time_micros
    ,cdi_override
    ,by_pass_mqr
    ,broker_name
    ,trading_company
    ,mic
    ,cc
    ,ingested_at
    ,created_at
    ,updated_at

FROM {{ source('ice_trade_blotters_v1', 'ice_trade_blotter_v1_2026_apr_02') }}
