version: 2

models:
  - name: source_v1_caiso_da_hrl_lmps
    description: "Normalized CAISO day-ahead hourly LMPs by hub (NP15, SP15)."
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'

  - name: source_v1_caiso_rt_hrl_lmps
    description: "Normalized CAISO real-time hourly LMPs by hub (NP15, SP15). 15-min data averaged to hourly."
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'
