version: 2

models:
  - name: isone_lmps_hourly
    description: '{{ doc("isone_mart_lmps_hourly") }}'
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("col_hour_ending") }}'
        tests:
          - not_null
      - name: hub
        description: "ISO-NE pricing hub name."
        tests:
          - not_null
      - name: market
        description: '{{ doc("col_market") }}'
        tests:
          - not_null
          - accepted_values:
              values: ['da', 'rt', 'dart']

  - name: isone_lmps_daily
    description: '{{ doc("isone_mart_lmps_daily") }}'
    columns:
      - name: date
        description: '{{ doc("col_date") }}'
        tests:
          - not_null
