version: 2

sources:

  - name: isone_v1
    schema: isone
    description: '{{ doc("isone_overview") }}'
    tables:
      - name: da_hrl_lmps
        description: "ISO-NE day-ahead hourly LMPs by location."
      - name: rt_hrl_lmps_final
        description: "ISO-NE real-time hourly LMPs (final/verified) by location."
      - name: rt_hrl_lmps_prelim
        description: "ISO-NE real-time hourly LMPs (preliminary) by location."
