select
  datetime_beginning_utc
  ,datetime_ending_utc
  ,timezone
  ,datetime_beginning_local
  ,datetime_ending_local
  ,date
  ,hour_ending
  ,coal
  ,gas
  ,hydro
  ,multiple_fuels
  ,nuclear
  ,oil
  ,solar
  ,storage
  ,wind
  ,other
  ,other_renewables
  ,total
  ,thermal
  ,renewables
  ,gas_pct_thermal
  ,coal_pct_thermal
from pjm_cleaned.pjm_fuel_mix_hourly
