select
  date
  ,period
  ,da_lmp_total_arkansas_hub
  ,rt_lmp_total_arkansas_hub
  ,dart_lmp_total_arkansas_hub
  ,da_lmp_total_illinois_hub
  ,rt_lmp_total_illinois_hub
  ,dart_lmp_total_illinois_hub
  ,da_lmp_total_indiana_hub
  ,rt_lmp_total_indiana_hub
  ,dart_lmp_total_indiana_hub
  ,da_lmp_total_louisiana_hub
  ,rt_lmp_total_louisiana_hub
  ,dart_lmp_total_louisiana_hub
  ,da_lmp_total_michigan_hub
  ,rt_lmp_total_michigan_hub
  ,dart_lmp_total_michigan_hub
  ,da_lmp_total_minn_hub
  ,rt_lmp_total_minn_hub
  ,dart_lmp_total_minn_hub
  ,da_lmp_total_ms_hub
  ,rt_lmp_total_ms_hub
  ,dart_lmp_total_ms_hub
  ,da_lmp_total_texas_hub
  ,rt_lmp_total_texas_hub
  ,dart_lmp_total_texas_hub
from miso_cleaned.miso_lmps_daily
