version: 2

models:
  - name: staging_v1_eia_930_hourly
    description: '{{ doc("eia_930_staging_hourly") }}'
    columns:
      - name: datetime_utc
        description: '{{ doc("eia_col_datetime_utc") }}'
        tests:
          - not_null
      - name: datetime
        description: '{{ doc("eia_col_datetime") }}'
        tests:
          - not_null
      - name: date
        description: '{{ doc("eia_col_date") }}'
        tests:
          - not_null
      - name: hour_ending
        description: '{{ doc("eia_col_hour_ending") }}'
        tests:
          - not_null
      - name: is_iso
        description: '{{ doc("eia_col_is_iso") }}'
      - name: time_zone
        description: '{{ doc("eia_col_time_zone") }}'
      - name: region
        description: '{{ doc("eia_col_region") }}'
      - name: respondent
        description: '{{ doc("eia_col_respondent") }}'
        tests:
          - not_null
      - name: balancing_authority_name
        description: '{{ doc("eia_col_balancing_authority_name") }}'
      - name: total
        description: '{{ doc("eia_col_total") }}'
      - name: renewables
        description: '{{ doc("eia_col_renewables") }}'
      - name: thermal
        description: '{{ doc("eia_col_thermal") }}'
      - name: wind
        description: '{{ doc("eia_col_wind") }}'
      - name: solar
        description: '{{ doc("eia_col_solar") }}'
      - name: natural_gas
        description: '{{ doc("eia_col_natural_gas") }}'
      - name: coal
        description: '{{ doc("eia_col_coal") }}'
      - name: oil
        description: '{{ doc("eia_col_oil") }}'
      - name: nuclear
        description: '{{ doc("eia_col_nuclear") }}'
      - name: hydro
        description: '{{ doc("eia_col_hydro") }}'
      - name: pumped_storage
        description: '{{ doc("eia_col_pumped_storage") }}'
      - name: geothermal
        description: '{{ doc("eia_col_geothermal") }}'
      - name: battery
        description: '{{ doc("eia_col_battery") }}'
      - name: solar_battery
        description: '{{ doc("eia_col_solar_battery") }}'
      - name: wind_battery
        description: '{{ doc("eia_col_wind_battery") }}'
      - name: other_energy_storage
        description: '{{ doc("eia_col_other_energy_storage") }}'
      - name: unknown_energy_storage
        description: '{{ doc("eia_col_unknown_energy_storage") }}'
      - name: other
        description: '{{ doc("eia_col_other") }}'
      - name: unknown
        description: '{{ doc("eia_col_unknown") }}'

  - name: staging_v1_eia_ng_consumption_by_end_use_monthly
    description: '{{ doc("eia_nat_gas_consumption_staging") }}'
    columns:
      - name: year
        description: '{{ doc("eia_ng_col_year") }}'
        tests:
          - not_null
      - name: month
        description: '{{ doc("eia_ng_col_month") }}'
        tests:
          - not_null
      - name: area_name_standardized
        description: '{{ doc("eia_ng_col_area_name_standardized") }}'
        tests:
          - not_null
      - name: consumption_unit
        description: '{{ doc("eia_ng_col_consumption_unit") }}'
        tests:
          - not_null
      - name: lease_and_plant_fuel
        description: '{{ doc("eia_ng_col_lease_and_plant_fuel") }}'
      - name: pipeline_and_distribution_use
        description: '{{ doc("eia_ng_col_pipeline_and_distribution_use") }}'
      - name: volumes_delivered_to_consumers
        description: '{{ doc("eia_ng_col_volumes_delivered_to_consumers") }}'
      - name: residential
        description: '{{ doc("eia_ng_col_residential") }}'
      - name: commercial
        description: '{{ doc("eia_ng_col_commercial") }}'
      - name: industrial
        description: '{{ doc("eia_ng_col_industrial") }}'
      - name: vehicle_fuel
        description: '{{ doc("eia_ng_col_vehicle_fuel") }}'
      - name: electric_power
        description: '{{ doc("eia_ng_col_electric_power") }}'
