# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_azure_postgresql'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_azure_postgresql'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# # ── triggers ────────────────────────────────────────────────────────────────────
# # Run triggers after every dbt run
# on-run-end:
#   - "{{ setup_postgres_triggers() }}"

# ── seeds ────────────────────────────────────────────────────────────────────
seeds:
  dbt_azure_postgresql:
    dbt_wsi_temps_v1_2026_feb_25:
      +schema: dbt_wsi_temps_v1_2026_feb_25

# ── Models ────────────────────────────────────────────────────────────────────
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_azure_postgresql:
  
    # ── dbt ────────────────────────────────────────────────────────────────────
    dbt:
      +schema: dbt
      +materialized: view

    # ── Positions and Trades ────────────────────────────────────────────────────
    positions_and_trades:
      trades_cleaned:
        +schema: trades_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      positions_cleaned:
        +schema: positions_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Meteologica ──────────────────────────────────────────────────────────────
    meteologica:
      meteologica_cleaned:
        +schema: meteologica_cleaned_v2
        +materialized: view
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view
          
      meteologica_pjm_cleaned:
        +schema: meteologica_pjm_cleaned_v2
        +materialized: view
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Power ──────────────────────────────────────────────────────────────────
    power:
      pjm_cleaned:
        +schema: pjm_cleaned_v2
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        queries:
          +materialized: ephemeral
        utils:
          +materialized: ephemeral
        marts:
          +materialized: view

      pjm_modelling:
        +schema: pjm_modelling
        +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: table

      ercot_cleaned:
        +schema: ercot_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      miso_cleaned:
        +schema: miso_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      caiso_cleaned:
        +schema: caiso_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      nyiso_cleaned:
        +schema: nyiso_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      spp_cleaned:
        +schema: spp_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

      isone_cleaned:
        +schema: isone_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── WSI ────────────────────────────────────────────────────────────────────
    wsi:
      wsi_cleaned:
        +schema: wsi_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Genscape ──────────────────────────────────────────────────────────────────
    genscape:
      genscape_cleaned:
        +schema: genscape_cleaned
        +materialized: view

    # ── EIA ──────────────────────────────────────────────────────────────────
    eia:
      eia_cleaned:
        +schema: eia_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        utils:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Energy Aspects ──────────────────────────────────────────────────────
    energy_aspects:
      energy_aspects_cleaned:
        +schema: energy_aspects_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── Bloomberg ──────────────────────────────────────────────────────────
    bloomberg:
      bbg_dapi_cleaned:
        +schema: bbg_dapi_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── ICE Trade Blotters ──────────────────────────────────────────────────
    ice_trade_blotters:
      ice_trade_blotters_cleaned:
        +schema: ice_trade_blotters_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: view

    # ── ICE Python ──────────────────────────────────────────────────────────
    ice_python:
      ice_python_cleaned:
        +schema: ice_python_cleaned
        +materialized: ephemeral
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        utils:
          +materialized: ephemeral
        marts:
          +materialized: view