dbt_azure_postgresql:
  target: azure_postgres
  outputs:
    azure_postgres:
      type: postgres
      host: "{{ env_var('AZURE_POSTGRESQL_DB_HOST') }}"
      dbname: "{{ env_var('AZURE_POSTGRESQL_DB_NAME') }}"
      user: "{{ env_var('AZURE_POSTGRESQL_DB_USER') }}"
      password: "{{ env_var('AZURE_POSTGRESQL_DB_PASSWORD') }}"
      port: "{{ env_var('AZURE_POSTGRESQL_DB_PORT') | int }}"
      schema: dbt
      threads: 12