select
  date
  -- NP15 DA
  ,da_lmp_total_np15_hub_flat
  ,da_lmp_total_np15_hub_onpeak
  ,da_lmp_total_np15_hub_offpeak
  ,da_lmp_system_energy_price_np15_hub_flat
  ,da_lmp_system_energy_price_np15_hub_onpeak
  ,da_lmp_system_energy_price_np15_hub_offpeak
  ,da_lmp_congestion_price_np15_hub_flat
  ,da_lmp_congestion_price_np15_hub_onpeak
  ,da_lmp_congestion_price_np15_hub_offpeak
  ,da_lmp_marginal_loss_price_np15_hub_flat
  ,da_lmp_marginal_loss_price_np15_hub_onpeak
  ,da_lmp_marginal_loss_price_np15_hub_offpeak
  -- NP15 RT
  ,rt_lmp_total_np15_hub_flat
  ,rt_lmp_total_np15_hub_onpeak
  ,rt_lmp_total_np15_hub_offpeak
  ,rt_lmp_system_energy_price_np15_hub_flat
  ,rt_lmp_system_energy_price_np15_hub_onpeak
  ,rt_lmp_system_energy_price_np15_hub_offpeak
  ,rt_lmp_congestion_price_np15_hub_flat
  ,rt_lmp_congestion_price_np15_hub_onpeak
  ,rt_lmp_congestion_price_np15_hub_offpeak
  ,rt_lmp_marginal_loss_price_np15_hub_flat
  ,rt_lmp_marginal_loss_price_np15_hub_onpeak
  ,rt_lmp_marginal_loss_price_np15_hub_offpeak
  -- NP15 DART
  ,dart_lmp_total_np15_hub_flat
  ,dart_lmp_total_np15_hub_onpeak
  ,dart_lmp_total_np15_hub_offpeak
  ,dart_lmp_system_energy_price_np15_hub_flat
  ,dart_lmp_system_energy_price_np15_hub_onpeak
  ,dart_lmp_system_energy_price_np15_hub_offpeak
  ,dart_lmp_congestion_price_np15_hub_flat
  ,dart_lmp_congestion_price_np15_hub_onpeak
  ,dart_lmp_congestion_price_np15_hub_offpeak
  ,dart_lmp_marginal_loss_price_np15_hub_flat
  ,dart_lmp_marginal_loss_price_np15_hub_onpeak
  ,dart_lmp_marginal_loss_price_np15_hub_offpeak
  -- SP15 DA
  ,da_lmp_total_sp15_hub_flat
  ,da_lmp_total_sp15_hub_onpeak
  ,da_lmp_total_sp15_hub_offpeak
  ,da_lmp_system_energy_price_sp15_hub_flat
  ,da_lmp_system_energy_price_sp15_hub_onpeak
  ,da_lmp_system_energy_price_sp15_hub_offpeak
  ,da_lmp_congestion_price_sp15_hub_flat
  ,da_lmp_congestion_price_sp15_hub_onpeak
  ,da_lmp_congestion_price_sp15_hub_offpeak
  ,da_lmp_marginal_loss_price_sp15_hub_flat
  ,da_lmp_marginal_loss_price_sp15_hub_onpeak
  ,da_lmp_marginal_loss_price_sp15_hub_offpeak
  -- SP15 RT
  ,rt_lmp_total_sp15_hub_flat
  ,rt_lmp_total_sp15_hub_onpeak
  ,rt_lmp_total_sp15_hub_offpeak
  ,rt_lmp_system_energy_price_sp15_hub_flat
  ,rt_lmp_system_energy_price_sp15_hub_onpeak
  ,rt_lmp_system_energy_price_sp15_hub_offpeak
  ,rt_lmp_congestion_price_sp15_hub_flat
  ,rt_lmp_congestion_price_sp15_hub_onpeak
  ,rt_lmp_congestion_price_sp15_hub_offpeak
  ,rt_lmp_marginal_loss_price_sp15_hub_flat
  ,rt_lmp_marginal_loss_price_sp15_hub_onpeak
  ,rt_lmp_marginal_loss_price_sp15_hub_offpeak
  -- SP15 DART
  ,dart_lmp_total_sp15_hub_flat
  ,dart_lmp_total_sp15_hub_onpeak
  ,dart_lmp_total_sp15_hub_offpeak
  ,dart_lmp_system_energy_price_sp15_hub_flat
  ,dart_lmp_system_energy_price_sp15_hub_onpeak
  ,dart_lmp_system_energy_price_sp15_hub_offpeak
  ,dart_lmp_congestion_price_sp15_hub_flat
  ,dart_lmp_congestion_price_sp15_hub_onpeak
  ,dart_lmp_congestion_price_sp15_hub_offpeak
  ,dart_lmp_marginal_loss_price_sp15_hub_flat
  ,dart_lmp_marginal_loss_price_sp15_hub_onpeak
  ,dart_lmp_marginal_loss_price_sp15_hub_offpeak
from caiso_cleaned.caiso_lmps_daily
