name: 'dbt_azure_postgresql'
version: '1.0.0'

profile: 'dbt_azure_postgresql'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_azure_postgresql:
    +schema: pjm_da_modelling_cleaned
    +materialized: ephemeral
    
    power:
      pjm:
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral
        _archive:
          +enabled: false

    meteologica:
      pjm:
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral
        _archive:
          +enabled: false

    ice_python:
      source:
        +materialized: ephemeral
      staging:
        +materialized: ephemeral
      marts:
        +materialized: ephemeral

    energy_aspects:
      energy_aspects_cleaned:
        source:
          +materialized: ephemeral
        staging:
          +materialized: ephemeral
        marts:
          +materialized: ephemeral

    wsi:
      source:
        +materialized: ephemeral
      staging:
        +materialized: ephemeral
      marts:
        +materialized: ephemeral

    scorecards:
      +materialized: view

    positions_and_trades:
      +materialized: ephemeral
      trades_cleaned:
        marts:
          +materialized: view
