version: 2

sources:

  - name: bbg_dapi_v1
    schema: bbg_dapi
    description: '{{ doc("bbg_dapi_overview") }}'
    tables:
      - name: bbg_tickers
        description: '{{ doc("bbg_dapi_tickers_source") }}'
      - name: bbg_historical
        description: '{{ doc("bbg_dapi_historical_source") }}'
        loaded_at_field: updated_at
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
