select
  sftp_date
  ,previous_sftp_date
  ,last_trade_date
  ,days_to_expiry
  ,exchange_name
  ,exchange_code_grouping
  ,exchange_code_region
  ,exchange_code
  ,exchange_code_underlying
  ,is_option
  ,put_call
  ,strike_price
  ,marex_delta
  ,previous_marex_delta
  ,contract_yyyymm
  ,contract_yyyymmdd
  ,contract_year
  ,contract_month
  ,contract_day
  ,futures_contract_month
  ,futures_contract_month_y
  ,futures_contract_month_yy
  ,marex_description
  ,ice_xl_symbol
  ,ice_xl_symbol_underlying
  ,cme_excel_symbol
  ,bbg_symbol
  ,bbg_option_description
  ,lots
  ,daily_pnl_total
  ,market_value_total
  ,previous_market_value_total
  ,settlement_price_total
  ,previous_settlement_price_total
  ,daily_change_total
  ,trade_price_total
  ,qty_total
  ,previous_qty_total
  ,dod_qty_total
  ,qty_acim
  ,qty_andy
  ,qty_mac
  ,qty_pnt
  ,qty_dickson
  ,qty_titan
from positions_cleaned.marex_and_nav_positions_grouped_latest
