select
  sftp_date
  ,sftp_upload_timestamp
  ,marex_reference_number
  ,account
  ,exchange_name
  ,exchange_code
  ,is_option
  ,put_call
  ,strike_price
  ,marex_delta
  ,contract_yyyymm
  ,contract_yyyymmdd
  ,contract_year
  ,contract_month
  ,contract_day
  ,trade_date
  ,last_trade_date
  ,marex_description
  ,buy_sell
  ,qty
  ,lots
  ,settlement_price
  ,trade_price
  ,market_value
from positions_cleaned.marex_positions
