select
  sftp_date
  ,sftp_upload_timestamp
  ,nav_reference_number
  ,account
  ,exchange_name
  ,exchange_code
  ,is_option
  ,put_call_long
  ,put_call
  ,strike_price
  ,contract_yyyymm
  ,contract_yyyymmdd
  ,contract_year
  ,contract_month
  ,contract_day
  ,trade_date
  ,last_trade_date
  ,nav_product
  ,buy_sell
  ,qty
  ,lots
  ,settlement_price
  ,trade_price
  ,market_value
from positions_cleaned.nav_positions_moross
