{{
  config(
    materialized='ephemeral'
  )
}}

---------------------------
-- BASE EXTRACT
---------------------------

-- WSI blend table: has _difference (single), _normal, _dfn
-- NWP model tables: have _6hr through _30hr_difference, _normal, _dfn

WITH RAW AS (
    SELECT
        init_time AS forecast_execution_datetime,
        init_time::DATE AS forecast_execution_date,
        period_start::DATE AS forecast_date,
        model,
        LPAD(EXTRACT(HOUR FROM init_time)::TEXT, 2, '0') || 'Z' AS cycle,
        bias_corrected,
        site_id AS region,
        electric_cdd::NUMERIC AS electric_cdd,
        electric_cdd_normal::NUMERIC AS electric_cdd_normal,
        electric_cdd_dfn::NUMERIC AS electric_cdd_dfn,
        electric_cdd_difference::NUMERIC AS electric_cdd_difference,
        NULL::NUMERIC AS electric_cdd_6hr_difference,
        NULL::NUMERIC AS electric_cdd_12hr_difference,
        NULL::NUMERIC AS electric_cdd_18hr_difference,
        NULL::NUMERIC AS electric_cdd_24hr_difference,
        NULL::NUMERIC AS electric_cdd_30hr_difference,
        electric_hdd::NUMERIC AS electric_hdd,
        electric_hdd_normal::NUMERIC AS electric_hdd_normal,
        electric_hdd_dfn::NUMERIC AS electric_hdd_dfn,
        electric_hdd_difference::NUMERIC AS electric_hdd_difference,
        NULL::NUMERIC AS electric_hdd_6hr_difference,
        NULL::NUMERIC AS electric_hdd_12hr_difference,
        NULL::NUMERIC AS electric_hdd_18hr_difference,
        NULL::NUMERIC AS electric_hdd_24hr_difference,
        NULL::NUMERIC AS electric_hdd_30hr_difference,
        gas_cdd::NUMERIC AS gas_cdd,
        gas_cdd_normal::NUMERIC AS gas_cdd_normal,
        gas_cdd_dfn::NUMERIC AS gas_cdd_dfn,
        gas_cdd_difference::NUMERIC AS gas_cdd_difference,
        NULL::NUMERIC AS gas_cdd_6hr_difference,
        NULL::NUMERIC AS gas_cdd_12hr_difference,
        NULL::NUMERIC AS gas_cdd_18hr_difference,
        NULL::NUMERIC AS gas_cdd_24hr_difference,
        NULL::NUMERIC AS gas_cdd_30hr_difference,
        gas_hdd::NUMERIC AS gas_hdd,
        gas_hdd_normal::NUMERIC AS gas_hdd_normal,
        gas_hdd_dfn::NUMERIC AS gas_hdd_dfn,
        gas_hdd_difference::NUMERIC AS gas_hdd_difference,
        NULL::NUMERIC AS gas_hdd_6hr_difference,
        NULL::NUMERIC AS gas_hdd_12hr_difference,
        NULL::NUMERIC AS gas_hdd_18hr_difference,
        NULL::NUMERIC AS gas_hdd_24hr_difference,
        NULL::NUMERIC AS gas_hdd_30hr_difference,
        population_cdd::NUMERIC AS pw_cdd,
        population_cdd_normal::NUMERIC AS pw_cdd_normal,
        population_cdd_dfn::NUMERIC AS pw_cdd_dfn,
        population_cdd_difference::NUMERIC AS pw_cdd_difference,
        NULL::NUMERIC AS pw_cdd_6hr_difference,
        NULL::NUMERIC AS pw_cdd_12hr_difference,
        NULL::NUMERIC AS pw_cdd_18hr_difference,
        NULL::NUMERIC AS pw_cdd_24hr_difference,
        NULL::NUMERIC AS pw_cdd_30hr_difference,
        population_hdd::NUMERIC AS pw_hdd,
        population_hdd_normal::NUMERIC AS pw_hdd_normal,
        population_hdd_dfn::NUMERIC AS pw_hdd_dfn,
        population_hdd_difference::NUMERIC AS pw_hdd_difference,
        NULL::NUMERIC AS pw_hdd_6hr_difference,
        NULL::NUMERIC AS pw_hdd_12hr_difference,
        NULL::NUMERIC AS pw_hdd_18hr_difference,
        NULL::NUMERIC AS pw_hdd_24hr_difference,
        NULL::NUMERIC AS pw_hdd_30hr_difference,
        created_at,
        updated_at
    FROM {{ source('wsi_v1', 'wsi_wdd_day_forecast_v2_2025_dec_17') }}
    WHERE init_time::DATE >= (CURRENT_TIMESTAMP AT TIME ZONE 'MST')::DATE - 365
        AND site_id IN ('CONUS', 'EAST', 'MIDWEST', 'MOUNTAIN', 'PACIFIC', 'SOUTHCENTRAL')

    UNION ALL

    SELECT
        init_time AS forecast_execution_datetime,
        init_time::DATE AS forecast_execution_date,
        period_start::DATE AS forecast_date,
        model,
        LPAD(EXTRACT(HOUR FROM init_time)::TEXT, 2, '0') || 'Z' AS cycle,
        bias_corrected,
        site_id AS region,
        electric_cdd::NUMERIC AS electric_cdd,
        electric_cdd_normal::NUMERIC AS electric_cdd_normal,
        electric_cdd_dfn::NUMERIC AS electric_cdd_dfn,
        NULL::NUMERIC AS electric_cdd_difference,
        electric_cdd_6hr_difference::NUMERIC AS electric_cdd_6hr_difference,
        electric_cdd_12hr_difference::NUMERIC AS electric_cdd_12hr_difference,
        electric_cdd_18hr_difference::NUMERIC AS electric_cdd_18hr_difference,
        electric_cdd_24hr_difference::NUMERIC AS electric_cdd_24hr_difference,
        electric_cdd_30hr_difference::NUMERIC AS electric_cdd_30hr_difference,
        electric_hdd::NUMERIC AS electric_hdd,
        electric_hdd_normal::NUMERIC AS electric_hdd_normal,
        electric_hdd_dfn::NUMERIC AS electric_hdd_dfn,
        NULL::NUMERIC AS electric_hdd_difference,
        electric_hdd_6hr_difference::NUMERIC AS electric_hdd_6hr_difference,
        electric_hdd_12hr_difference::NUMERIC AS electric_hdd_12hr_difference,
        electric_hdd_18hr_difference::NUMERIC AS electric_hdd_18hr_difference,
        electric_hdd_24hr_difference::NUMERIC AS electric_hdd_24hr_difference,
        electric_hdd_30hr_difference::NUMERIC AS electric_hdd_30hr_difference,
        gas_cdd::NUMERIC AS gas_cdd,
        gas_cdd_normal::NUMERIC AS gas_cdd_normal,
        gas_cdd_dfn::NUMERIC AS gas_cdd_dfn,
        NULL::NUMERIC AS gas_cdd_difference,
        gas_cdd_6hr_difference::NUMERIC AS gas_cdd_6hr_difference,
        gas_cdd_12hr_difference::NUMERIC AS gas_cdd_12hr_difference,
        gas_cdd_18hr_difference::NUMERIC AS gas_cdd_18hr_difference,
        gas_cdd_24hr_difference::NUMERIC AS gas_cdd_24hr_difference,
        gas_cdd_30hr_difference::NUMERIC AS gas_cdd_30hr_difference,
        gas_hdd::NUMERIC AS gas_hdd,
        gas_hdd_normal::NUMERIC AS gas_hdd_normal,
        gas_hdd_dfn::NUMERIC AS gas_hdd_dfn,
        NULL::NUMERIC AS gas_hdd_difference,
        gas_hdd_6hr_difference::NUMERIC AS gas_hdd_6hr_difference,
        gas_hdd_12hr_difference::NUMERIC AS gas_hdd_12hr_difference,
        gas_hdd_18hr_difference::NUMERIC AS gas_hdd_18hr_difference,
        gas_hdd_24hr_difference::NUMERIC AS gas_hdd_24hr_difference,
        gas_hdd_30hr_difference::NUMERIC AS gas_hdd_30hr_difference,
        population_cdd::NUMERIC AS pw_cdd,
        population_cdd_normal::NUMERIC AS pw_cdd_normal,
        population_cdd_dfn::NUMERIC AS pw_cdd_dfn,
        NULL::NUMERIC AS pw_cdd_difference,
        population_cdd_6hr_difference::NUMERIC AS pw_cdd_6hr_difference,
        population_cdd_12hr_difference::NUMERIC AS pw_cdd_12hr_difference,
        population_cdd_18hr_difference::NUMERIC AS pw_cdd_18hr_difference,
        population_cdd_24hr_difference::NUMERIC AS pw_cdd_24hr_difference,
        population_cdd_30hr_difference::NUMERIC AS pw_cdd_30hr_difference,
        population_hdd::NUMERIC AS pw_hdd,
        population_hdd_normal::NUMERIC AS pw_hdd_normal,
        population_hdd_dfn::NUMERIC AS pw_hdd_dfn,
        NULL::NUMERIC AS pw_hdd_difference,
        population_hdd_6hr_difference::NUMERIC AS pw_hdd_6hr_difference,
        population_hdd_12hr_difference::NUMERIC AS pw_hdd_12hr_difference,
        population_hdd_18hr_difference::NUMERIC AS pw_hdd_18hr_difference,
        population_hdd_24hr_difference::NUMERIC AS pw_hdd_24hr_difference,
        population_hdd_30hr_difference::NUMERIC AS pw_hdd_30hr_difference,
        created_at,
        updated_at
    FROM {{ source('wsi_v1', 'gfs_op_wdd_day_forecast_v2_2025_dec_17') }}
    WHERE init_time::DATE >= (CURRENT_TIMESTAMP AT TIME ZONE 'MST')::DATE - 365
        AND site_id IN ('CONUS', 'EAST', 'MIDWEST', 'MOUNTAIN', 'PACIFIC', 'SOUTHCENTRAL')

    UNION ALL

    SELECT
        init_time AS forecast_execution_datetime,
        init_time::DATE AS forecast_execution_date,
        period_start::DATE AS forecast_date,
        model,
        LPAD(EXTRACT(HOUR FROM init_time)::TEXT, 2, '0') || 'Z' AS cycle,
        bias_corrected,
        site_id AS region,
        electric_cdd::NUMERIC AS electric_cdd,
        electric_cdd_normal::NUMERIC AS electric_cdd_normal,
        electric_cdd_dfn::NUMERIC AS electric_cdd_dfn,
        NULL::NUMERIC AS electric_cdd_difference,
        electric_cdd_6hr_difference::NUMERIC AS electric_cdd_6hr_difference,
        electric_cdd_12hr_difference::NUMERIC AS electric_cdd_12hr_difference,
        electric_cdd_18hr_difference::NUMERIC AS electric_cdd_18hr_difference,
        electric_cdd_24hr_difference::NUMERIC AS electric_cdd_24hr_difference,
        electric_cdd_30hr_difference::NUMERIC AS electric_cdd_30hr_difference,
        electric_hdd::NUMERIC AS electric_hdd,
        electric_hdd_normal::NUMERIC AS electric_hdd_normal,
        electric_hdd_dfn::NUMERIC AS electric_hdd_dfn,
        NULL::NUMERIC AS electric_hdd_difference,
        electric_hdd_6hr_difference::NUMERIC AS electric_hdd_6hr_difference,
        electric_hdd_12hr_difference::NUMERIC AS electric_hdd_12hr_difference,
        electric_hdd_18hr_difference::NUMERIC AS electric_hdd_18hr_difference,
        electric_hdd_24hr_difference::NUMERIC AS electric_hdd_24hr_difference,
        electric_hdd_30hr_difference::NUMERIC AS electric_hdd_30hr_difference,
        gas_cdd::NUMERIC AS gas_cdd,
        gas_cdd_normal::NUMERIC AS gas_cdd_normal,
        gas_cdd_dfn::NUMERIC AS gas_cdd_dfn,
        NULL::NUMERIC AS gas_cdd_difference,
        gas_cdd_6hr_difference::NUMERIC AS gas_cdd_6hr_difference,
        gas_cdd_12hr_difference::NUMERIC AS gas_cdd_12hr_difference,
        gas_cdd_18hr_difference::NUMERIC AS gas_cdd_18hr_difference,
        gas_cdd_24hr_difference::NUMERIC AS gas_cdd_24hr_difference,
        gas_cdd_30hr_difference::NUMERIC AS gas_cdd_30hr_difference,
        gas_hdd::NUMERIC AS gas_hdd,
        gas_hdd_normal::NUMERIC AS gas_hdd_normal,
        gas_hdd_dfn::NUMERIC AS gas_hdd_dfn,
        NULL::NUMERIC AS gas_hdd_difference,
        gas_hdd_6hr_difference::NUMERIC AS gas_hdd_6hr_difference,
        gas_hdd_12hr_difference::NUMERIC AS gas_hdd_12hr_difference,
        gas_hdd_18hr_difference::NUMERIC AS gas_hdd_18hr_difference,
        gas_hdd_24hr_difference::NUMERIC AS gas_hdd_24hr_difference,
        gas_hdd_30hr_difference::NUMERIC AS gas_hdd_30hr_difference,
        population_cdd::NUMERIC AS pw_cdd,
        population_cdd_normal::NUMERIC AS pw_cdd_normal,
        population_cdd_dfn::NUMERIC AS pw_cdd_dfn,
        NULL::NUMERIC AS pw_cdd_difference,
        population_cdd_6hr_difference::NUMERIC AS pw_cdd_6hr_difference,
        population_cdd_12hr_difference::NUMERIC AS pw_cdd_12hr_difference,
        population_cdd_18hr_difference::NUMERIC AS pw_cdd_18hr_difference,
        population_cdd_24hr_difference::NUMERIC AS pw_cdd_24hr_difference,
        population_cdd_30hr_difference::NUMERIC AS pw_cdd_30hr_difference,
        population_hdd::NUMERIC AS pw_hdd,
        population_hdd_normal::NUMERIC AS pw_hdd_normal,
        population_hdd_dfn::NUMERIC AS pw_hdd_dfn,
        NULL::NUMERIC AS pw_hdd_difference,
        population_hdd_6hr_difference::NUMERIC AS pw_hdd_6hr_difference,
        population_hdd_12hr_difference::NUMERIC AS pw_hdd_12hr_difference,
        population_hdd_18hr_difference::NUMERIC AS pw_hdd_18hr_difference,
        population_hdd_24hr_difference::NUMERIC AS pw_hdd_24hr_difference,
        population_hdd_30hr_difference::NUMERIC AS pw_hdd_30hr_difference,
        created_at,
        updated_at
    FROM {{ source('wsi_v1', 'gfs_ens_wdd_day_forecast_v2_2025_dec_17') }}
    WHERE init_time::DATE >= (CURRENT_TIMESTAMP AT TIME ZONE 'MST')::DATE - 365
        AND site_id IN ('CONUS', 'EAST', 'MIDWEST', 'MOUNTAIN', 'PACIFIC', 'SOUTHCENTRAL')

    UNION ALL

    SELECT
        init_time AS forecast_execution_datetime,
        init_time::DATE AS forecast_execution_date,
        period_start::DATE AS forecast_date,
        model,
        LPAD(EXTRACT(HOUR FROM init_time)::TEXT, 2, '0') || 'Z' AS cycle,
        bias_corrected,
        site_id AS region,
        electric_cdd::NUMERIC AS electric_cdd,
        electric_cdd_normal::NUMERIC AS electric_cdd_normal,
        electric_cdd_dfn::NUMERIC AS electric_cdd_dfn,
        NULL::NUMERIC AS electric_cdd_difference,
        electric_cdd_6hr_difference::NUMERIC AS electric_cdd_6hr_difference,
        electric_cdd_12hr_difference::NUMERIC AS electric_cdd_12hr_difference,
        electric_cdd_18hr_difference::NUMERIC AS electric_cdd_18hr_difference,
        electric_cdd_24hr_difference::NUMERIC AS electric_cdd_24hr_difference,
        electric_cdd_30hr_difference::NUMERIC AS electric_cdd_30hr_difference,
        electric_hdd::NUMERIC AS electric_hdd,
        electric_hdd_normal::NUMERIC AS electric_hdd_normal,
        electric_hdd_dfn::NUMERIC AS electric_hdd_dfn,
        NULL::NUMERIC AS electric_hdd_difference,
        electric_hdd_6hr_difference::NUMERIC AS electric_hdd_6hr_difference,
        electric_hdd_12hr_difference::NUMERIC AS electric_hdd_12hr_difference,
        electric_hdd_18hr_difference::NUMERIC AS electric_hdd_18hr_difference,
        electric_hdd_24hr_difference::NUMERIC AS electric_hdd_24hr_difference,
        electric_hdd_30hr_difference::NUMERIC AS electric_hdd_30hr_difference,
        gas_cdd::NUMERIC AS gas_cdd,
        gas_cdd_normal::NUMERIC AS gas_cdd_normal,
        gas_cdd_dfn::NUMERIC AS gas_cdd_dfn,
        NULL::NUMERIC AS gas_cdd_difference,
        gas_cdd_6hr_difference::NUMERIC AS gas_cdd_6hr_difference,
        gas_cdd_12hr_difference::NUMERIC AS gas_cdd_12hr_difference,
        gas_cdd_18hr_difference::NUMERIC AS gas_cdd_18hr_difference,
        gas_cdd_24hr_difference::NUMERIC AS gas_cdd_24hr_difference,
        gas_cdd_30hr_difference::NUMERIC AS gas_cdd_30hr_difference,
        gas_hdd::NUMERIC AS gas_hdd,
        gas_hdd_normal::NUMERIC AS gas_hdd_normal,
        gas_hdd_dfn::NUMERIC AS gas_hdd_dfn,
        NULL::NUMERIC AS gas_hdd_difference,
        gas_hdd_6hr_difference::NUMERIC AS gas_hdd_6hr_difference,
        gas_hdd_12hr_difference::NUMERIC AS gas_hdd_12hr_difference,
        gas_hdd_18hr_difference::NUMERIC AS gas_hdd_18hr_difference,
        gas_hdd_24hr_difference::NUMERIC AS gas_hdd_24hr_difference,
        gas_hdd_30hr_difference::NUMERIC AS gas_hdd_30hr_difference,
        population_cdd::NUMERIC AS pw_cdd,
        population_cdd_normal::NUMERIC AS pw_cdd_normal,
        population_cdd_dfn::NUMERIC AS pw_cdd_dfn,
        NULL::NUMERIC AS pw_cdd_difference,
        population_cdd_6hr_difference::NUMERIC AS pw_cdd_6hr_difference,
        population_cdd_12hr_difference::NUMERIC AS pw_cdd_12hr_difference,
        population_cdd_18hr_difference::NUMERIC AS pw_cdd_18hr_difference,
        population_cdd_24hr_difference::NUMERIC AS pw_cdd_24hr_difference,
        population_cdd_30hr_difference::NUMERIC AS pw_cdd_30hr_difference,
        population_hdd::NUMERIC AS pw_hdd,
        population_hdd_normal::NUMERIC AS pw_hdd_normal,
        population_hdd_dfn::NUMERIC AS pw_hdd_dfn,
        NULL::NUMERIC AS pw_hdd_difference,
        population_hdd_6hr_difference::NUMERIC AS pw_hdd_6hr_difference,
        population_hdd_12hr_difference::NUMERIC AS pw_hdd_12hr_difference,
        population_hdd_18hr_difference::NUMERIC AS pw_hdd_18hr_difference,
        population_hdd_24hr_difference::NUMERIC AS pw_hdd_24hr_difference,
        population_hdd_30hr_difference::NUMERIC AS pw_hdd_30hr_difference,
        created_at,
        updated_at
    FROM {{ source('wsi_v1', 'ecmwf_op_wdd_day_forecast_v2_2025_dec_17') }}
    WHERE init_time::DATE >= (CURRENT_TIMESTAMP AT TIME ZONE 'MST')::DATE - 365
        AND site_id IN ('CONUS', 'EAST', 'MIDWEST', 'MOUNTAIN', 'PACIFIC', 'SOUTHCENTRAL')

    UNION ALL

    SELECT
        init_time AS forecast_execution_datetime,
        init_time::DATE AS forecast_execution_date,
        period_start::DATE AS forecast_date,
        model,
        LPAD(EXTRACT(HOUR FROM init_time)::TEXT, 2, '0') || 'Z' AS cycle,
        bias_corrected,
        site_id AS region,
        electric_cdd::NUMERIC AS electric_cdd,
        electric_cdd_normal::NUMERIC AS electric_cdd_normal,
        electric_cdd_dfn::NUMERIC AS electric_cdd_dfn,
        NULL::NUMERIC AS electric_cdd_difference,
        electric_cdd_6hr_difference::NUMERIC AS electric_cdd_6hr_difference,
        electric_cdd_12hr_difference::NUMERIC AS electric_cdd_12hr_difference,
        electric_cdd_18hr_difference::NUMERIC AS electric_cdd_18hr_difference,
        electric_cdd_24hr_difference::NUMERIC AS electric_cdd_24hr_difference,
        electric_cdd_30hr_difference::NUMERIC AS electric_cdd_30hr_difference,
        electric_hdd::NUMERIC AS electric_hdd,
        electric_hdd_normal::NUMERIC AS electric_hdd_normal,
        electric_hdd_dfn::NUMERIC AS electric_hdd_dfn,
        NULL::NUMERIC AS electric_hdd_difference,
        electric_hdd_6hr_difference::NUMERIC AS electric_hdd_6hr_difference,
        electric_hdd_12hr_difference::NUMERIC AS electric_hdd_12hr_difference,
        electric_hdd_18hr_difference::NUMERIC AS electric_hdd_18hr_difference,
        electric_hdd_24hr_difference::NUMERIC AS electric_hdd_24hr_difference,
        electric_hdd_30hr_difference::NUMERIC AS electric_hdd_30hr_difference,
        gas_cdd::NUMERIC AS gas_cdd,
        gas_cdd_normal::NUMERIC AS gas_cdd_normal,
        gas_cdd_dfn::NUMERIC AS gas_cdd_dfn,
        NULL::NUMERIC AS gas_cdd_difference,
        gas_cdd_6hr_difference::NUMERIC AS gas_cdd_6hr_difference,
        gas_cdd_12hr_difference::NUMERIC AS gas_cdd_12hr_difference,
        gas_cdd_18hr_difference::NUMERIC AS gas_cdd_18hr_difference,
        gas_cdd_24hr_difference::NUMERIC AS gas_cdd_24hr_difference,
        gas_cdd_30hr_difference::NUMERIC AS gas_cdd_30hr_difference,
        gas_hdd::NUMERIC AS gas_hdd,
        gas_hdd_normal::NUMERIC AS gas_hdd_normal,
        gas_hdd_dfn::NUMERIC AS gas_hdd_dfn,
        NULL::NUMERIC AS gas_hdd_difference,
        gas_hdd_6hr_difference::NUMERIC AS gas_hdd_6hr_difference,
        gas_hdd_12hr_difference::NUMERIC AS gas_hdd_12hr_difference,
        gas_hdd_18hr_difference::NUMERIC AS gas_hdd_18hr_difference,
        gas_hdd_24hr_difference::NUMERIC AS gas_hdd_24hr_difference,
        gas_hdd_30hr_difference::NUMERIC AS gas_hdd_30hr_difference,
        population_cdd::NUMERIC AS pw_cdd,
        population_cdd_normal::NUMERIC AS pw_cdd_normal,
        population_cdd_dfn::NUMERIC AS pw_cdd_dfn,
        NULL::NUMERIC AS pw_cdd_difference,
        population_cdd_6hr_difference::NUMERIC AS pw_cdd_6hr_difference,
        population_cdd_12hr_difference::NUMERIC AS pw_cdd_12hr_difference,
        population_cdd_18hr_difference::NUMERIC AS pw_cdd_18hr_difference,
        population_cdd_24hr_difference::NUMERIC AS pw_cdd_24hr_difference,
        population_cdd_30hr_difference::NUMERIC AS pw_cdd_30hr_difference,
        population_hdd::NUMERIC AS pw_hdd,
        population_hdd_normal::NUMERIC AS pw_hdd_normal,
        population_hdd_dfn::NUMERIC AS pw_hdd_dfn,
        NULL::NUMERIC AS pw_hdd_difference,
        population_hdd_6hr_difference::NUMERIC AS pw_hdd_6hr_difference,
        population_hdd_12hr_difference::NUMERIC AS pw_hdd_12hr_difference,
        population_hdd_18hr_difference::NUMERIC AS pw_hdd_18hr_difference,
        population_hdd_24hr_difference::NUMERIC AS pw_hdd_24hr_difference,
        population_hdd_30hr_difference::NUMERIC AS pw_hdd_30hr_difference,
        created_at,
        updated_at
    FROM {{ source('wsi_v1', 'ecmwf_ens_wdd_day_forecast_v2_2025_dec_17') }}
    WHERE init_time::DATE >= (CURRENT_TIMESTAMP AT TIME ZONE 'MST')::DATE - 365
        AND site_id IN ('CONUS', 'EAST', 'MIDWEST', 'MOUNTAIN', 'PACIFIC', 'SOUTHCENTRAL')

),

FINAL AS (
    SELECT * FROM RAW
)

SELECT * FROM FINAL
