version: 2

models:

  # ===========================
  # Demand Forecast
  # ===========================

  - name: staging_v1_meteo_pjm_load_forecast_hourly
    description: '{{ doc("meteologica_pjm_demand_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
      - name: forecast_execution_datetime_utc
        description: '{{ doc("col_forecast_execution_datetime_utc") }}'
      - name: timezone
        description: '{{ doc("col_timezone") }}'
      - name: forecast_execution_datetime_local
        description: '{{ doc("col_forecast_execution_datetime_local") }}'
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
      - name: forecast_datetime_ending_utc
        description: '{{ doc("col_forecast_datetime_ending_utc") }}'
      - name: forecast_datetime_ending_local
        description: '{{ doc("col_forecast_datetime_ending_local") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
      - name: region
        description: '{{ doc("col_meteologica_region") }}'
      - name: forecast_load_mw
        description: '{{ doc("col_forecast_load_mw") }}'

  # ===========================
  # Solar Generation Forecast
  # ===========================

  - name: staging_v1_meteo_pjm_solar_forecast_hourly
    description: '{{ doc("meteologica_pjm_generation_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
      - name: forecast_execution_datetime_utc
        description: '{{ doc("col_forecast_execution_datetime_utc") }}'
      - name: timezone
        description: '{{ doc("col_timezone") }}'
      - name: forecast_execution_datetime_local
        description: '{{ doc("col_forecast_execution_datetime_local") }}'
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
      - name: forecast_datetime_ending_utc
        description: '{{ doc("col_forecast_datetime_ending_utc") }}'
      - name: forecast_datetime_ending_local
        description: '{{ doc("col_forecast_datetime_ending_local") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
      - name: region
        description: '{{ doc("col_meteologica_region") }}'
      - name: forecast_generation_mw
        description: '{{ doc("col_forecast_generation_mw") }}'

  # ===========================
  # Wind Generation Forecast
  # ===========================

  - name: staging_v1_meteo_pjm_wind_forecast_hourly
    description: '{{ doc("meteologica_pjm_generation_forecast") }}'
    columns:
      - name: forecast_rank
        description: '{{ doc("col_meteologica_forecast_rank") }}'
      - name: forecast_execution_datetime_utc
        description: '{{ doc("col_forecast_execution_datetime_utc") }}'
      - name: timezone
        description: '{{ doc("col_timezone") }}'
      - name: forecast_execution_datetime_local
        description: '{{ doc("col_forecast_execution_datetime_local") }}'
      - name: forecast_execution_date
        description: '{{ doc("col_forecast_execution_date") }}'
      - name: forecast_datetime_ending_utc
        description: '{{ doc("col_forecast_datetime_ending_utc") }}'
      - name: forecast_datetime_ending_local
        description: '{{ doc("col_forecast_datetime_ending_local") }}'
      - name: forecast_date
        description: '{{ doc("col_forecast_date") }}'
      - name: hour_ending
        description: '{{ doc("col_meteologica_hour_ending") }}'
      - name: region
        description: '{{ doc("col_meteologica_region") }}'
      - name: forecast_generation_mw
        description: '{{ doc("col_forecast_generation_mw") }}'
