version: 2

sources:
  - name: clear_street_v2
    schema: clear_street
    description: '{{ doc("trades_clear_street_source_group") }}'
    tables:
      - name: helios_transactions_v2_2026_feb_23
        description: '{{ doc("trades_source_clear_street_transactions") }}'
      - name: helios_intraday_transactions_v2_2026_feb_23
        description: '{{ doc("trades_source_clear_street_intraday_transactions") }}'

  - name: marex_v2
    schema: marex
    description: '{{ doc("trades_marex_source_group") }}'
    tables:
      - name: helios_allocated_trades_v2_2026_feb_23
        description: '{{ doc("trades_source_marex_allocated_trades") }}'
