version: 2

sources:

  - name: gridstatus_v1
    schema: gridstatus
    description: '{{ doc("caiso_overview") }}'
    tables:
      - name: caiso_lmp_day_ahead_hourly
        description: "CAISO day-ahead hourly LMPs by location from GridStatus."
      - name: caiso_lmp_real_time_15_min
        description: "CAISO real-time 15-minute LMPs by location from GridStatus."
