version: 2

sources:
  - name: marex_v5
    schema: marex
    description: '{{ doc("positions_marex_source_group") }}'
    tables:
      - name: marex_sftp_positions_v2_2026_feb_23
        description: '{{ doc("positions_source_marex_positions") }}'

  - name: nav_v5
    schema: nav
    description: '{{ doc("positions_nav_source_group") }}'
    tables:
      - name: nav_sftp_positions_agr_v2_2026_feb_23
        description: '{{ doc("positions_source_nav_agr_positions") }}'
      - name: nav_sftp_positions_moross_v2_2026_feb_23
        description: '{{ doc("positions_source_nav_moross_positions") }}'
      - name: nav_sftp_positions_pnt_v2_2026_feb_23
        description: '{{ doc("positions_source_nav_pnt_positions") }}'
      - name: nav_sftp_positions_titan_v2_2026_feb_23
        description: '{{ doc("positions_source_nav_titan_positions") }}'
